### ISSUE TITLE
Service stopped and cannot be started

### ISSUE THREAD

**Issue by DerekFangming** [BarsikV/CommunicationDeviceSwitcherService#1]
I'm getting this error when installing with admin mode. Anything wrong that I'm doing?
I installed .Net run time from the link you provided (it's version 5.0 tho), and restarted several times. The service remains stopped and cannot be manually started

```
Status   Name               DisplayName
------   ----               -----------
Stopped  CommunicationAu... Communication Audio Auto Switch Ser...
Start-Service : Service 'Communication Audio Auto Switch Service (CommunicationAudioAutoSwitchService)' cannot be
started due to the following error: Cannot start service CommunicationAudioAutoSwitchService on computer '.'.
At C:\CommunicationDeviceSwitcherService\Install service script.ps1:16 char:1
+ Start-Service $params.Name
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OpenError: (System.ServiceProcess.ServiceController:ServiceController) [Start-Service],
   ServiceCommandException
    + FullyQualifiedErrorId : CouldNotStartService,Microsoft.PowerShell.Commands.StartServiceCommand
```

**Comment by Remboooo** [comment]
The problem is that the installer script expects the application to be located in `C:\CommunicationDeviceSwitcherService`. Either move it there, or change the path in the installer script (you can edit it in notepad)

**Comment by BarsikV** [comment]
Hello, please try the new release, it should install everything right away in the right places and check for the right .netframework runtime. 
[https://github.com/BarsikV/CommunicationDeviceSwitcherService/releases/tag/1.0.1](Release  #1.0.1)
