### ISSUE TITLE
Add same function of this service for the recording device

### ISSUE THREAD

**Issue by HughTsao** [BarsikV/CommunicationDeviceSwitcherService#3]
As the title says, Can you make same function of the service for recording device, Thanks a lot!

**Comment by BarsikV** [comment]
Hello, yes, I think it is possible.

**Comment by cerahmed** [comment]
Any update for changing the Recording device? I can confirm that the latest release only works for Default Output.
Recording/input devices on the other hand are still separate.

**Comment by BarsikV** [comment]
Added support for microphones in latest beta release. Will close this after merging the pull request. 
https://github.com/BarsikV/CommunicationDeviceSwitcherService/releases/tag/2.0.3-beta
