### ISSUE TITLE
How to install? (for noobs)

### ISSUE THREAD

**Issue by reily-cleiane** [BarsikV/CommunicationDeviceSwitcherService#4]
I would like to use this program but I don't know how. Could someone please explain (to noobs) how to install?

**Comment by blanelegant** [comment]
Just figured this out myself and got it working. You'll have to compile it.

You'll need to download Visual Studio 2019 Community, checkout the repo, and double-click the solution (`.sln` file) in the Solution Explorer (View -> Solution Explorer). Then follow the prompts to install necessary dependencies. It prompted me to install .NET, which I did, then after that I had to install allow NuGet to install missing packages. If that prompt doesn't show up you can right click on the solution in the Solution Explorer box on the right and click "Restore NuGet Packages". If that fails you'll need to add the NuGet repository (for some reason on my install it wasn't there by default, see [here](https://stackoverflow.com/a/69045467). Then "Restore NuGet Packages" should work. Finally, press the "ComminicationDeviceSwitcherService" button (green play icon) on the toolbar and it should run.

To install you should do a non-debug build and then run the provided PowerShell script in the root of the project directory with Administrator privileges. If you encounter an error with that you'll probably need to set your machine's `ExecutionPolicy` to allow non-signed local scripts, see [here](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.security/set-executionpolicy?view=powershell-7.2#example-1--set-an-execution-policy). This command needs to be run from an Administrator PowerShell prompt as well.

I'm not super great with Windows dev tools myself so I  figured I'd be verbose with the details, hope this helps.

**Comment by blanelegant** [comment]
Actually, there is a [releases page](https://github.com/BarsikV/CommunicationDeviceSwitcherService/releases) where you can download an installer in case you don't want to go through that trouble.
